receivers:
  filelog/apache:
    include: [ "./test/apache.log" ]
    start_at: beginning

  filelog/syslog:
    include: [ "./test/syslog.log" ]
    start_at: beginning

  filelog/asa:
    include: [ "./test/asa.log" ]
    start_at: beginning

  filelog/cisco_ise:
    include: [ "./test/cisco_ise.log" ]
    start_at: beginning

  filelog/cisco_ios:
    include: [ "./test/cisco_ios.log" ]
    start_at: beginning

processors:
  apache_grok:
    pattern: "%{COMBINEDAPACHELOG}"
    pattern_directory: ./patterns

  syslog_grok:
    pattern: "%{SYSLOGBASE}"
    pattern_directory: ./patterns

  grokproc:
    pattern: "%{ASA302014}"
    pattern_directory: ./patterns
    field_map:
      src: "source.ip"
      dst: "destination.ip"
    extract_cef: true

  cisco_ise_grok:
    pattern: "%{CISCO_ISE_SYSLOG_1}"
    pattern_directory: ./patterns

  cisco_ios_grok:
    pattern: "%{CISCO_IOS_SYSLOG1}"
    pattern_directory: ./patterns

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs/apache:
      receivers: [ filelog/apache ]
      processors: [ apache_grok ]
      exporters: [ logging ]

    logs/syslog:
      receivers: [ filelog/syslog ]
      processors: [ syslog_grok ]
      exporters: [ logging ]

    logs/asa:
      receivers: [ filelog/asa ]
      processors: [ grokproc ]
      exporters: [ logging ]

    logs/cisco_ise:
      receivers: [ filelog/cisco_ise ]
      processors: [ cisco_ise_grok ]
      exporters: [ logging ]

    logs/cisco_ios:
      receivers: [ filelog/cisco_ios ]
      processors: [ cisco_ios_grok ]
      exporters: [ logging ]