package main

// Auto-generated regex patterns for log parsing
// Generated by rawregexgen

const (
	// Pattern1 - from java-logs.txt
	// Sample: 2025-05-20 18:16:13,463 [WebContainer : 5 ] INFO c.c.s.p.PaymentInstantCreditComponentImpl - heartbeat(true)
	// Groups: date, time, context, level, class, method, value
	Pattern1 = `^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2},\d{3}) \[(?P<context>[^\]]+)\] (?P<level>[A-Z]+) (?P<class>[\w\.]+) - (?P<method>\w+)\((?P<value>[^)]*)\)$`

	// Pattern2 - from samplelogs.txt
	// Sample: 488 <166>1 2025-05-15T13:42:19-07:00 INA400 LEEF - - - 1.0|Raz-Lee iSecurity|Audit|1.0|MCD0300|usrName=EDIOPR devTime=2025-05-15-13.42.19.436 devTimeFormat=yyyy-MM-dd-HH.mm.ss.SSS source=*LCL-ED850EBLD sev=4 jobName=759738/EDIOPR/ED850EBLD pgmName=CED031 pgmLib=EDI5VMIPGM entryType=CD/C entryDesc=A command was run Sequence_number=0738078059 Port=00000 Name_of_object=RCVMSG Library_name=QSYS Object_type=*CMD Run_from_CL/REXX=Y Command_string=RCVMSG RMV(*NO) MSGDTA(&MSGDTA) MSGID(&MSGID)
	// Groups: date, time, num
	Pattern2 = `^(?P<num>\d+) <166>1 (?P<date>\d{4}-\d{2}-\d{2})T(?P<time>\d{2}:\d{2}:\d{2}(?:[.,:]\d{3})?)-07:00 INA400 LEEF - - - 1\.0\|Raz-Lee iSecurity\|Audit\|1\.0\|MCD0300\|usrName=EDIOPR devTime=2025-05-15-13\.42\.19\.436 devTimeFormat=yyyy-MM-dd-HH\.mm\.ss\.SSS source=\*LCL-ED850EBLD sev=4 jobName=759738/EDIOPR/ED850EBLD pgmName=CED031 pgmLib=EDI5VMIPGM entryType=CD/C entryDesc=A command was run Sequence_number=0738078059 Port=00000 Name_of_object=RCVMSG Library_name=QSYS Object_type=\*CMD Run_from_CL/REXX=Y Command_string=RCVMSG RMV\(\*NO\) MSGDTA\(&MSGDTA\) MSGID\(&MSGID\)$`

	// Pattern3 - from samplelogs.txt
	// Sample: net.host.ip 172.23.250.212
	// Groups: num
	Pattern3 = `^net\.host\.ip (?P<num>\d+)\.23\.250\.212$`

	// Pattern4 - from samplelogs.txt
	// Sample: net.host.port 6005
	// Groups: num
	Pattern4 = `^net\.host\.port (?P<num>\d+)$`

	// Pattern5 - from samplelogs.txt
	// Sample: net.peer.ip 172.23.250.155
	// Groups: num
	Pattern5 = `^net\.peer\.ip (?P<num>\d+)\.23\.250\.155$`

	// Pattern6 - from samplelogs.txt
	// Sample: net.peer.name 172.23.250.155
	// Groups: num
	Pattern6 = `^net\.peer\.name (?P<num>\d+)\.23\.250\.155$`

	// Pattern7 - from samplelogs.txt
	// Sample: net.peer.port 36577
	// Groups: num
	Pattern7 = `^net\.peer\.port (?P<num>\d+)$`

	// Pattern8 - from samplelogs.txt
	// Sample: observed_time 2025-05-15T20:42:19.8622536Z
	// Groups: date, time, num
	Pattern8 = `^observed_time (?P<date>\d{4}-\d{2}-\d{2})T(?P<time>\d{2}:\d{2}:\d{2}(?:[.,:]\d{3})?)2536Z$`

	// Pattern9 - from samplelogs.txt
	// Sample: time 1970-01-01T00:00:00Z
	// Groups: date, time, num
	Pattern9 = `^time (?P<date>\d{4}-\d{2}-\d{2})T(?P<time>\d{2}:\d{2}:\d{2}(?:[.,:]\d{3})?)Z$`
)
